<?php  

/* 
 * the main menu for Hip Chat archive
 * hook_menu
 */
function hipchat_archive_menu() {
  $items = array();

  $items['hipchat-archive/%/%'] = array(
    'title' => 'Hip chat Archive',
    'description' => 'displays archives of Hip chat',
    'page callback' => '_hipchat_archive_get_data',
    'access callback' => TRUE,
    'page arguments' => array(1,2),
    'title' => 'Archives',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}
 
/*
 * _hipchat_archive_get_data
 * parameter = $date 
 * if no parameter is given, the default would be today
 * The date of the format(yyyy-mm-dd) is sent to the apichat
 * service and chat history retrieved for that date
 */
function _hipchat_archive_get_data($date = Null, $room_id = 575239){
  //variable declaration
  $link = 'https://api.hipchat.com/v1/rooms/history?room_id='; 
  $output = '';
  $authToken = '&auth_token=f9f12e58a0df9ed77e14094a5eacb1';
  $time_zone = 'America/New_York';
  $format = 'json';
  $currDate = date('Y-m-d');
  $formattedData = '';

  //check date 
  //if the date clicked is either null or today's date
  //make the current date as today with next day as null
  //else the date clicked can only be less than the current date
  if ($date == Null || $date >= $currDate){
    // $currDate = '2014-05-30';
    $date = $currDate;
    $nextDate ='';
    
    if ($date > $currDate) {
      drupal_set_message(t('Cannot retrieve data for date beyond today'), 'error');
    }
  }
  else{
    $nextDate = date('Y-m-d', strtotime($date .' +1 day'));
  }
  
  $prevDate = date('Y-m-d', strtotime($date .' -1 day')); 
  
  try {
    //get history from api.hipchat.com for the parameters
    $chatData = file_get_contents($link.$room_id.'&date='.$date.'&timezone='.$time_zone.'&format='.$format.$authToken);
  }
  catch(Exception $e){
    drupal_set_message(t('Issue in retrieving the data. Message = %message, query=%query', 
    array('%message' =>$e->getMessage(),'%query' => $e->query_string)), 'error');
  }
  
  //format the data 
  $formattedData = _hipchat_archive_format_data($prevDate,$date,$chatData,$nextDate);

  //return the formatted data
  return $formattedData;
}
  
/*
 * format_ChatData
 * parameter = $prevDate, $todayDate, $data, $nextDate
 * formats the data and returns the data in a table format
 * $prevDate,$nextDate are used for creating links
 * $todayDate is used for showing the user that the date on a 
 * page is for that date and hence not a link
 * $data is the chat history for the date selected
 */
function _hipchat_archive_format_data($prevDate,$todayDate,$data,$nextDate){
  //variable declaration
  $rows = array();
  $prevLink = l(t($prevDate), 'hipchat-archive/'.$prevDate.'/');
  $nextLink = l(t($nextDate), 'hipchat-archive/'.$nextDate.'/');

  //get data from the 
  $output = drupal_json_decode($data);
  
  //create the header for the table
  $header = array('From','Message','Date');
  $result = $output['messages'];
  //put data into rows
  foreach($result as $data) {
    $rows[] = array(
          $data['from']['name'],
          $data['message'],
          $data['date'],
    );
  }

  //add space between links
  $spaces = str_repeat('&nbsp;', 75);
  //format output with links on the top of the table
  $output = $prevLink.$spaces.$todayDate.$spaces.$nextLink;
  $output .=  theme('table', array('header' => $header, 'rows' => $rows));

  //return formatted output
  return $output;
  }